import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Multi Step Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Ubuntu:100,200,300,400,500,600,700,800"
          rel="stylesheet"
        ></link>
      </head>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
